{{- if .Values.otel.logs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-logs-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  logs.config: |
{{ tpl (.Files.Get "logs-collector-config.yaml") . | indent 8 }}
{{- end }}