version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: docker
    directory: /build/docker
    labels:
      - dependencies
      - docker
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "solarwinds-otel-collector"
    schedule:
      interval: "daily"
