version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: docker
    directory: /build/docker
    labels:
      - dependencies
      - docker
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /src/cmd
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    ignore:
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector-contrib*"
      - dependency-name: "go.opentelemetry.io/collector*"
    groups:
      minor-and-patch:
        applies-to: security-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"
  - package-ecosystem: gomod
    directory: /src/processor/k8sattributesprocessor
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector-contrib*"
      - dependency-name: "go.opentelemetry.io/collector*"
  - package-ecosystem: gomod
    directory: /src/processor/swmetricstransformprocessor
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
    ignore:
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector-contrib*"
      - dependency-name: "go.opentelemetry.io/collector*"
