docker:
  - changed-files:
      - any-glob-to-any-file:
          - build/*
          - src/*
helm:
  - changed-files:
      - any-glob-to-any-file:
          - deploy/*
documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/*"
      - any-glob-to-any-file: "*.md"
