changelog:
  exclude:
    labels:
      - Skip Changelog
      - ci/cd
    authors: []
  categories:
    - title: Helm Chart Updates
      labels:
        - helm
    - title: Docker Image Updates
      labels:
        - docker
        - dependencies