changelog:
  exclude:
    labels:
      - skip-changelog
    authors: []
  categories:
    - title: Helm Chart Updates
      labels:
        - helm
    - title: Docker Image Updates
      labels:
        - docker
        - dependencies