apiVersion: skaffold/v3
kind: Config
metadata:
  name: swi-k8s-opentelemetry-collector
build:
  artifacts:
  - image: swi-k8s-opentelemetry-collector
    docker:
      dockerfile: build/docker/Dockerfile
  local:
    push: false
manifests:
  helm:
    releases:
    - name: monitoring
      remoteChart: prometheus
      namespace: monitoring
      createNamespace: true
      repo: https://prometheus-community.github.io/helm-charts
  kustomize:
    paths:
    - tests/deploy/base
    buildArgs:
    - --load-restrictor LoadRestrictionsNone
deploy:
  kubectl: {}
  helm: {}
  kubeContext: docker-desktop
profiles:
- name: builder-only
  build:
    artifacts:
    - image: swi-k8s-opentelemetry-collector-builder
      docker:
        dockerfile: build/docker/Dockerfile
        target: builder
        buildArgs:
          CREATE_VENDOR_DIR: "true"
    local:
      push: false
- name: ci
  activation:
  - env: CI=true
  build:
    local:
      push: false
      useBuildkit: true
      concurrency: 0
  deploy:
    # `default` is k3s default context name
    kubeContext: default
