apiVersion: skaffold/v3
kind: Config
metadata:
  name: swi-k8s-opentelemetry-collector
build:
  artifacts:
    - image: integration-test
      docker:
        dockerfile: build/docker/IntegrationTest.Dockerfile
        buildArgs: 
          CI: "{{ .CI }}"
  local:
    push: false
deploy:
  helm:
    releases:
      - name: timeseries-mock-service
        chartPath: tests/deploy/timeseries-mock-service
        namespace: test-namespace
        createNamespace: true
        upgradeOnChange: true
      - name: sut
        chartPath: deploy/helm
        namespace: test-namespace
        createNamespace: true
        setValueTemplates:
          cluster:
            name: "cluster name"
            uid: "cluster-uid-123456789"
          otel:
            endpoint: timeseries-mock-service:9082
            tls_insecure: true
            # OTEL collector requires the SOLARWINDS_API_TOKEN env variable to be set to some not empty string
            api_token: "not_set"
            node_collector:
              sending_queue:
                persistent_storage:
                  enabled: true
            metrics:
              prometheus_check: false
              sending_queue:
                offload_to_disk: true
              prometheus:
                scrape_interval: "15s"
              kube-state-metrics:
                scrape_interval: "15s"
              control_plane:
                controller_manager:
                  enabled: false
                etcd:
                  enabled: false
              autodiscovery:
                prometheusEndpoints: 
                  filter:
                    exclude:
                      match_type: regexp
                      metric_names:
                        - k8s.otelcol_processor.*
                  podMonitors:
                    rules:
                      - rule: labels["app"] == "test-deployment"
                        metrics_path: "/custom_metrics"
                        endpoint_port: 8081
                prefix: ""
            events:
              sending_queue:
                offload_to_disk: true
            manifests:
              pull_every: 1m
              persistent_storage:
                enabled: false
            logs:
              # journal on Docker Desktop is not supported
              journal: false
              filter:
                log_record:
                  - resource.attributes["k8s.namespace.name"] == "test-namespace"
        upgradeOnChange: true
      # Deploy prometheus for development purposes. Metrics prefixed with `output_` contains metrics produced by the agent
      - name: timeseries-mock-service-custom-resources
        chartPath: tests/deploy/timeseries-mock-service-custom-resources
        namespace: test-namespace
        createNamespace: true
        upgradeOnChange: true
      - name: monitoring
        remoteChart: kube-prometheus-stack
        namespace: test-namespace
        createNamespace: true
        repo: https://prometheus-community.github.io/helm-charts
        version: 69.3.2
        setValues:
          alertmanager.enabled: false
          grafana.enabled: false
          nodeExporter.enabled: false
          kubeStateMetrics.enabled: false
          server:
            nodeSelector:
              "kubernetes\\.io\\/os": linux
      - name: tests
        chartPath: tests/deploy/tests
        namespace: test-namespace
        createNamespace: true
        upgradeOnChange: true
  kubeContext: docker-desktop
portForward:
- resourceType: service
  resourceName: timeseries-mock-service
  namespace: test-namespace
  port: 8088
- resourceType: service
  resourceName: prometheus-operated
  namespace: test-namespace
  port: 9090
  localPort: 8080
profiles:
  - name: build-collector
    build:
      artifacts:
        - image: swi-k8s-opentelemetry-collector
          # Path to cloned https://github.com/solarwinds/solarwinds-otel-collector.git repo
          context: ../solarwinds-otel-collector
          docker:
            dockerfile: build/docker/Dockerfile.k8s
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.image.repository
        value: "swi-k8s-opentelemetry-collector"
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.image.tag
        value: "{{.IMAGE_TAG}}"
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.image.pullPolicy
        value: "Never"
  - name: test-cluster
    patches:
    # remove timeseries-mock-service
    - op: remove
      path: /deploy/helm/releases/0
    # remove timeseries-mock-service-custom-resources
    - op: remove
      path: /deploy/helm/releases/1
    - op: replace
      path: /deploy/helm/releases/0/namespace
      value: "{{.TEST_CLUSTER_NAMESPACE}}"
    - op: replace
      path: /deploy/helm/releases/0/name
      value: "{{.TEST_CLUSTER_RELEASE_NAME}}"
    - op: replace
      path: /portForward/0/namespace
      value: "{{.TEST_CLUSTER_NAMESPACE}}"
    - op: replace
      path: /portForward/1/namespace
      value: "{{.TEST_CLUSTER_NAMESPACE}}"
    - op: replace
      path: /portForward/1/resourceName
      value: "{{.TEST_CLUSTER_RELEASE_NAME}}-prometheus-server"
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: "{{.TEST_CLUSTER_NAMESPACE}}"
    - op: remove
      path: /manifests/kustomize/paths/0
    - op: replace
      path: /deploy/helm/releases/1/namespace
      value: "{{.TEST_CLUSTER_NAMESPACE}}"
    - op: replace
      path: /deploy/helm/releases/1/name
      value: "{{.TEST_CLUSTER_RELEASE_NAME}}-prometheus"
    - op: replace
      path: /deploy/kubeContext
      value: "<your kube context here>"
  - name: operator
    activation:
      - env: CI=true
    resourceSelector:
      allow:
        # let skaffold to manager CRDs in local k8s
        - groupKind: "OpenTelemetryCollector.opentelemetry.io"
          image: [".*"]
          labels: [".*"]
        - groupKind: "PodMonitor.monitoring.coreos.com"
          image: [".*"]
          labels: [".*"]
        - groupKind: "ServiceMonitor.monitoring.coreos.com"
          image: [".*"]
          labels: [".*"]
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/operator.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/certmanager.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.metrics.autodiscovery.discovery_collector.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/prometheusCRDs.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/4/setValueTemplates
        value: 
          podMonitors:
            enabled: true
      - op: add
        path: /deploy/helm/releases/2/setValueTemplates
        value: 
          podMonitors:
            enabled: true
      - op: add
        path: /deploy/helm/hooks
        value:
          before:
            - host:
                command: ["sh", "-c", "./utils/pre-deploy.sh"]
                os: [darwin, linux]
            - host:
                command: ["cmd", "/c", ".\\utils\\pre-deploy.bat || exit 0"]
                os: [windows]
  - name: beyla
    activation:
      - env: CI=true
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/beyla.enabled
        value: true
  - name: no-logs
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.logs.enabled
        value: false
  - name: no-ebpf
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/ebpfNetworkMonitoring.enabled
        value: false
  - name: no-metrics
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.metrics.enabled
        value: false
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/kube-state-metrics.enabled
        value: false
  - name: no-events
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/otel.events.enabled
        value: false
  - name: no-tests
    patches:
      - op: remove
        path: /deploy/helm/releases/4
      - op: remove
        path: /build/artifacts/0
  - name: ci
    activation:
      - env: CI=true
    build:
      local:
        push: false
        useBuildkit: true
        concurrency: 0
    patches:
    # remove `monitoring` (Prometheus Operator)
    - op: remove
      path: /deploy/helm/releases/3
    - op: remove
      path: /portForward/1
    deploy:
      kubeContext: default
  - name: ci-helm-e2e
    build:
      local:
        push: false
        useBuildkit: true
        concurrency: 0
    deploy:
      # `default` is k3s default context name
      kubeContext: default
