apiVersion: v2
name: swo-k8s-collector
version: 4.2.0-alpha.6
appVersion: 0.11.7
description: SolarWinds Kubernetes Integration
keywords:
  - monitoring
  - observability
  - metric
  - logs
  - events
  - kubernetes
home: https://solarwinds.com/
icon: https://helm.solarwinds.com/favicon.png
sources:
  - https://github.com/solarwinds/swi-k8s-opentelemetry-collector/deploy/helm/
maintainers:
  - name: SolarWinds
    email: support@solarwinds.com
dependencies:
  - name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: "~> 5.25.1"
    condition: kube-state-metrics.enabled
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ebpf-kernelCollector
      image: solarwinds/opentelemetry-ebpf-kernel-collector:v0.10.2
      whitelisted: true
    - name: ebpf-k8sCollectorWatcher
      image: solarwinds/opentelemetry-ebpf-k8s-watcher:v0.10.2
      whitelisted: true
    - name: ebpf-k8sCollectorRelay
      image: solarwinds/opentelemetry-ebpf-k8s-relay:v0.10.2
      whitelisted: true
    - name: ebpf-reducer
      image: solarwinds/opentelemetry-ebpf-reducer:v0.10.2
      whitelisted: true
