apiVersion: v1
name: swi-k8s-opentelemetry-collector
version: 0.1.0
appVersion: "1"
description: SolarWinds Kubernetes Integration
keywords:
- monitoring
- alerting
- metric
home: https://solarwinds.com/
icon: https://www.solarwinds.com/favicon.ico
sources:
- https://github.com/solarwinds/swi-k8s-opentelemetry-collector/deploy/helm/
maintainers:
- name: SolarWinds
  email: support@solarwinds.com
