exporters:
  otlp:
    endpoint: ${OTEL_ENVOY_ADDRESS}
    tls:
      insecure: ${OTEL_ENVOY_ADDRESS_TLS_INSECURE}
    headers:
      "Authorization": "Bearer ${SOLARWINDS_API_TOKEN}"
extensions:
  file_storage:
{{ toYaml .Values.otel.logs.filestorage | indent 4 }}
  health_check: {}
{{- if .Values.otel.logs.memory_ballast }}
  memory_ballast:
{{ toYaml .Values.otel.logs.memory_ballast | indent 4 }}
{{- end }}
{{- if and .Values.otel.metrics.enabled .Values.otel.metrics.autodiscovery.prometheusEndpoints.enabled }}
  k8s_observer:
    auth_type: serviceAccount
    node: ${NODE_NAME}
    observe_pods: true
    observe_nodes: false
{{- end }}

processors:
  memory_limiter:
{{ toYaml .Values.otel.logs.memory_limiter | indent 4 }}

{{- if .Values.otel.logs.filter }}
  # For more all the options about the filtering see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor
  filter:
    logs:
{{ toYaml .Values.otel.logs.filter | indent 6 }}
{{- end }}

  groupbyattrs/all:
    keys:
      - k8s.container.name
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.pod.uid
      - host.name
      - service.name

  resource/all:
    attributes:

      # Collector and Manifest version
      - key: sw.k8s.agent.manifest.version
        value: ${MANIFEST_VERSION}
        action: insert

      - key: sw.k8s.agent.app.version
        value: ${APP_VERSION}
        action: insert

      # Cluster
      - key: sw.k8s.cluster.uid
        value: ${CLUSTER_UID}
        action: insert

      - key: k8s.cluster.name
        value: ${CLUSTER_NAME}
        action: insert

      # Node
      - key: k8s.node.name
        value: ${NODE_NAME}
        action: insert

  resource/container:
    attributes:

      - key: sw.k8s.log.type
        value: container
        action: insert

      # Collector and Manifest version
      - key: sw.k8s.agent.manifest.version
        value: ${MANIFEST_VERSION}
        action: insert

      - key: sw.k8s.agent.app.version
        value: ${APP_VERSION}
        action: insert

      # Cluster
      - key: sw.k8s.cluster.uid
        value: ${CLUSTER_UID}
        action: insert

      - key: k8s.cluster.name
        value: ${CLUSTER_NAME}
        action: insert

      # Node
      - key: k8s.node.name
        value: ${NODE_NAME}
        action: insert
{{- if and (not .isWindows) .Values.otel.logs.journal }}
  resource/journal:
    attributes:

      - key: sw.k8s.log.type
        value: journal
        action: insert

      # Collector and Manifest version
      - key: sw.k8s.agent.manifest.version
        value: ${MANIFEST_VERSION}
        action: insert

      - key: sw.k8s.agent.app.version
        value: ${APP_VERSION}
        action: insert

      # Cluster
      - key: sw.k8s.cluster.uid
        value: ${CLUSTER_UID}
        action: insert

      - key: k8s.cluster.name
        value: ${CLUSTER_NAME}
        action: insert

      # Node
      - key: k8s.node.name
        value: ${NODE_NAME}
        action: insert
{{- end }}
  transform/syslogify:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set( attributes["host.name"], attributes["k8s.pod.name"])
          - set( attributes["service.name"], attributes["k8s.container.name"])

  batch:
{{ toYaml .Values.otel.logs.batch | indent 4 }}

  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      node_from_env_var: NODE_NAME
    extract:
      metadata:
        - k8s.deployment.name
        - k8s.replicaset.name
        - k8s.daemonset.name
        - k8s.job.name
        - k8s.cronjob.name
        - k8s.statefulset.name
      labels:
        - key_regex: (.*)
          tag_name: k8s.pod.labels.$$1
          from: pod
        - key_regex: (.*)
          tag_name: k8s.namespace.labels.$$1
          from: namespace
      annotations:
        - key_regex: (.*)
          tag_name: k8s.pod.annotations.$$1
          from: pod
        - key_regex: (.*)
          tag_name: k8s.namespace.annotations.$$1
          from: namespace
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name

  metricstransform/rename:
    transforms:
      # add `k8s.` prefix to all metrics
      - include: ^(.*)$$
        match_type: regexp
        action: update
        new_name: k8s.$${1}

receivers:
{{- if and (not .isWindows) .Values.otel.logs.journal }}
  journald/runlogs:
    directory: /run/log/journal
    units:
      - kubelet
      - docker
      - containerd
  journald/varlogs:
    directory: /var/log/journal
    units:
      - kubelet
      - docker
      - containerd
{{- end}}
  filelog:
{{- if (.isWindows) }}
    include: [ "\\var\\log\\pods\\*\\*\\*.log" ]
    exclude: [ "\\var\\log\\pods\\${POD_NAMESPACE}_${POD_NAME}*_*\\swi-opentelemetry-collector\\*.log" ]
{{- else }}
    include: [ "/var/log/pods/*/*/*.log" ]
    # Exclude collector container's logs. The file format is /var/log/pods/<namespace_name>_<pod_name>_<pod_uid>/<container_name>/<run_id>.log    
    exclude: [ "/var/log/pods/${POD_NAMESPACE}_${POD_NAME}*_*/swi-opentelemetry-collector/*.log" ]
{{- end }}
    start_at: {{ .Values.otel.logs.receiver.start_at }}
    include_file_path: true
    include_file_name: false
    storage: file_storage
    max_log_size: {{ .Values.otel.logs.receiver.max_log_size }}
    max_concurrent_files: {{ .Values.otel.logs.receiver.max_concurrent_files }}
    fingerprint_size: {{ .Values.otel.logs.receiver.fingerprint_size }}
    encoding: {{ .Values.otel.logs.receiver.encoding }}
    poll_interval: {{ .Values.otel.logs.receiver.poll_interval }}
    operators:
      # Find out which format is used by kubernetes
      - type: router
        id: get-format
        routes:
          - output: parser-docker
            expr: 'body matches "^\\{"'
          - output: parser-crio
            expr: 'body matches "^[^ Z]+ "'
          - output: parser-containerd
            expr: 'body matches "^[^ Z]+Z"'
      # Parse CRI-O format
      - type: regex_parser
        id: parser-crio
        regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*)( |)(?P<log>.*)$'
        output: merge-cri-lines
        parse_to: body
        timestamp:
          parse_from: body.time
          layout_type: gotime
          layout: '2006-01-02T15:04:05.999999999-07:00'
      # Parse CRI-Containerd format
      - type: regex_parser
        id: parser-containerd
        regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*)( |)(?P<log>.*)$'
        output: merge-cri-lines
        parse_to: body
        timestamp:
          parse_from: body.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      # Parse Docker format
      - type: json_parser
        id: parser-docker
        parse_to: body
        output: merge-docker-lines
        timestamp:
          parse_from: body.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'

      # Merge log lines split by Docker logging driver.
      - type: recombine
        id: merge-docker-lines
        source_identifier: attributes["log.file.path"]
        output: merge-multiline-logs
        combine_field: body.log
        combine_with: ""
        is_last_entry: body.log matches "\n$"

      # Merge log lines split by CRI logging drivers.
      - type: recombine
        id: merge-cri-lines
        source_identifier: attributes["log.file.path"]
        output: merge-multiline-logs
        combine_field: body.log
        combine_with: ""
        is_last_entry: body.logtag == "F"
        overwrite_with: newest

      # Merges incoming log records into multiline logs.
      - type: recombine
        id: merge-multiline-logs
        output: extract-metadata-from-filepath
        source_identifier: attributes["log.file.path"]
        combine_field: body.log
        combine_with: ""
        is_first_entry: body.log matches "^\\[?\\d{4}-\\d{1,2}-\\d{1,2}.\\d{2}:\\d{2}:\\d{2}.*"

      # Extract metadata from file path
      - type: regex_parser
        id: extract-metadata-from-filepath
{{- if (.isWindows) }}
        regex: '^.*\\(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\\(?P<container_name>[^\._]+)\\(?P<run_id>\d+)\.log$'
{{- else }}
        regex:  '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$'
{{- end }}
        parse_from: attributes["log.file.path"]

      # Rename attributes
      - type: move
        id: move-attributes
        from: body.stream
        to: attributes["stream"]
      - type: move
        from: attributes.container_name
        to: attributes["k8s.container.name"]
      - type: move
        from: attributes.namespace
        to: attributes["k8s.namespace.name"]
      - type: move
        from: attributes.pod_name
        to: attributes["k8s.pod.name"]
      - type: remove
        field: attributes.run_id
      - type: move
        from: attributes.uid
        to: attributes["k8s.pod.uid"]
      - type: remove
        field: attributes["log.file.path"]
      - type: remove
        field: body.time
      - type: move
        from: body.log
        to: body

{{- if and .Values.otel.metrics.enabled .Values.otel.metrics.autodiscovery.prometheusEndpoints.enabled }}
  receiver_creator:
    watch_observers: 
      - k8s_observer
    receivers:
      prometheus:
        {{- if .Values.otel.metrics.autodiscovery.prometheusEndpoints.additionalRules }}
        rule: type == "pod" && annotations["prometheus.io/scrape"] == "true" && {{ .Values.otel.metrics.autodiscovery.prometheusEndpoints.additionalRules }}
        {{- else }}
        rule: type == "pod" && annotations["prometheus.io/scrape"] == "true"
        {{- end }} 
        config:
          config:
            scrape_configs:
              - job_name: pod
                scheme: "http"
                scrape_interval: {{ quote .Values.otel.metrics.prometheus.scrape_interval }}
                metrics_path: '`"prometheus.io/path" in annotations ? annotations["prometheus.io/path"] : "/metrics"`'
                honor_timestamps: false
                honor_labels: true
                static_configs:
                  - targets:
                      - '`endpoint`:`"prometheus.io/port" in annotations ? annotations["prometheus.io/port"] : 9090`'
{{- end }}

service:
  extensions:
    - file_storage
    - health_check
{{- if .Values.otel.logs.memory_ballast }}
    - memory_ballast
{{- end}}
{{- if and .Values.otel.metrics.enabled .Values.otel.metrics.autodiscovery.prometheusEndpoints.enabled }}
    - k8s_observer
{{- end}}
  pipelines:
{{- if .Values.otel.logs.container }}
    logs:
      exporters:
        - otlp
      processors:
        - memory_limiter
{{- if .Values.otel.logs.filter }}
        - filter
{{- end }}
        - transform/syslogify
        - groupbyattrs/all
        - resource/container
        - batch
      receivers:
        - filelog
{{- end }}
{{- if and (not .isWindows) .Values.otel.logs.journal }}
    logs/2:
      exporters:
        - otlp
      processors:
        - memory_limiter
        - groupbyattrs/all
        - resource/journal
        - batch
      receivers:
        - journald/runlogs
        - journald/varlogs
{{- end }}
{{- if and .Values.otel.metrics.enabled .Values.otel.metrics.autodiscovery.prometheusEndpoints.enabled }}
    metrics:
      exporters:
        - otlp
      processors:
        - memory_limiter
        - metricstransform/rename
        - groupbyattrs/all
        - resource/all
        - k8sattributes
        - batch
      receivers:
        - receiver_creator
{{- end }}
  telemetry:
{{- if .Values.otel.logs.telemetry.logs.enabled }}
    logs:
      level: {{ .Values.otel.logs.telemetry.logs.level }}
{{- end }}
{{- if .Values.otel.logs.telemetry.metrics.enabled }}
    metrics:
      address: {{ .Values.otel.logs.telemetry.metrics.address }}
{{- end }}
