{{- if .Values.ebpfNetworkMonitoring.enabled }}
{{- if not .Values.otel.gateway.enabled }}
{{- fail "The ebpfNetworkMonitoring.k8sCollector requires otel.gateway.enabled to be set to true" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" (tuple . "-network-k8s-reducer") }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "common.fullname" (tuple . "-network-k8s-reducer") }}
  template:
    metadata:
      labels:
        app: {{ include "common.fullname" (tuple . "-network-k8s-reducer") }}
{{ include "common.labels" . | indent 8 }}
{{ include "common.pod-labels" . | indent 8 }}
      annotations:
        checksum/values: {{ toJson .Values | sha256sum }}
{{ include "common.annotations" . | indent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-gateway
          image: "{{ include "common.image" (tuple . .Values.otel.init_images "busy_box") }}"
          imagePullPolicy: {{ .Values.otel.init_images.busy_box.pullPolicy }}
          command: ['sh', '-c', 'until nc -zv $GATEWAY_HOST $GATEWAY_PORT; do echo "Waiting for gateway endpoint..."; sleep 5; done;']
          env:
            - name: "GATEWAY_HOST"
              value: "{{ include "common.fullname" (tuple . "-gateway") }}"
            - name: "GATEWAY_PORT"
              value: "{{ .Values.otel.gateway.otlp_endpoint.port }}"
      containers:
        - name: reducer
          image: "{{ include "common.image" (tuple . .Values.ebpfNetworkMonitoring.reducer (tuple "image" "ebpf_reducer")) }}"
          imagePullPolicy: {{ .Values.ebpfNetworkMonitoring.reducer.image.pullPolicy }}
          args:
            - --port={{ .Values.ebpfNetworkMonitoring.reducer.telemetryPort }}
            - --log-console
            - --no-log-file
            - --{{ .Values.ebpfNetworkMonitoring.reducer.telemetry.logs.level }}
            - --enable-aws-enrichment
            {{- if .Values.ebpfNetworkMonitoring.reducer.enableIdIdGeneration }}
            - --enable-id-id
            {{- end }}
            - --disable-prometheus-metrics
            - --enable-otlp-grpc-metrics
            - --otlp-grpc-metrics-host={{ include "common.fullname" (tuple . "-gateway") }}
            - --otlp-grpc-metrics-port={{ .Values.otel.gateway.otlp_endpoint.port }}
            - --num-ingest-shards={{ .Values.ebpfNetworkMonitoring.reducer.numIngestShards }}
            - --num-matching-shards={{ .Values.ebpfNetworkMonitoring.reducer.numMatchingShards }}
            - --num-aggregation-shards={{ .Values.ebpfNetworkMonitoring.reducer.numAggregationShards }}
            {{- if .Values.ebpfNetworkMonitoring.reducer.disableMetrics }}
            - --disable-metrics={{join "," .Values.ebpfNetworkMonitoring.reducer.disableMetrics}}
            {{- end }}
            {{- if .Values.ebpfNetworkMonitoring.reducer.enableMetrics }}
            - --enable-metrics={{join "," .Values.ebpfNetworkMonitoring.reducer.enableMetrics}}
            {{- end }}
          env:
            - name: "EBPF_NET_CRASH_METRIC_HOST"
              value: "{{ include "common.fullname" (tuple . "-gateway") }}"
            - name: "EBPF_NET_CRASH_METRIC_PORT"
              value: "{{ .Values.otel.gateway.otlp_endpoint.port }}"
          ports:
            - name: telemetry
              containerPort: {{ .Values.ebpfNetworkMonitoring.reducer.telemetryPort }}
              protocol: TCP
          volumeMounts:
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 5
            exec:
              command: ['/srv/health_check.sh', 'readiness_probe', 'localhost', "{{ .Values.ebpfNetworkMonitoring.reducer.telemetryPort }}"]
          resources:
            null
      volumes:
{{- end}}