name: 'Deploy skaffold'
description: 'Deployes skaffold tool'
runs:
  using: 'composite'
  steps:
    - name: Setup skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
      shell: bash



