{{- if .Values.otel.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" (tuple . "-gateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: swo-k8s-collector
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.otel.gateway.autoscaler.minReplicas }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" (tuple . "-gateway") }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swo-k8s-collector
        app: {{ include "common.fullname" (tuple . "-gateway") }}
{{ include "common.labels" . | indent 8 }}
{{ include "common.pod-labels" . | indent 8 }}
      annotations:
        checksum/config: {{ tpl (.Files.Get "gateway-collector-config.yaml") . | sha256sum }}
        checksum/values: {{ toJson .Values | sha256sum }}
{{ include "common.annotations" . | indent 8 }}
{{- if .Values.otel.gateway.telemetry.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ (split ":" .Values.otel.gateway.telemetry.metrics.address)._1 | quote }}
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
{{- end}}
    spec:
      terminationGracePeriodSeconds: {{ .Values.otel.gateway.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "common.fullname" . }}
      securityContext:
        fsGroup: 10001
      {{- if .Values.otel.gateway.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.otel.gateway.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.otel.gateway.tolerations }}
      tolerations:
      {{ toYaml .Values.otel.gateway.tolerations | nindent 8 }}
      {{- end }}
      affinity:
      {{- if .Values.otel.gateway.affinity }}
      {{- toYaml .Values.otel.gateway.affinity | nindent 8 }}
      {{- else }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if include "isSwiEndpointCheckEnabled" . }}
      initContainers:
        - name: otel-endpoint-check
          image: "{{ include "common.image" (tuple . .Values.otel "image" nil (printf "%s-k8s" .Chart.AppVersion)) }}"
          imagePullPolicy: {{ .Values.otel.image.pullPolicy }}
          command:
            - /solarwinds-otel-collector
            - test-connection
            - --endpoint=$(OTEL_ENVOY_ADDRESS)
            - --apitoken=$(SOLARWINDS_API_TOKEN)
            - --clusteruid=$(CLUSTER_UID)
            - --insecure=$(OTEL_ENVOY_ADDRESS_TLS_INSECURE)
          env:
            - name: SOLARWINDS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.secret" . }}
                  key: SOLARWINDS_API_TOKEN
                  optional: true
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" (tuple . "-common-env") }}
      {{- end }}
      containers:
        - name: swi-opentelemetry-collector
          command:
            - /solarwinds-otel-collector
            - --config=/conf/gateway.config
          securityContext: 
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
          image: "{{ include "common.image" (tuple . .Values.otel "image" nil (printf "%s-k8s" .Chart.AppVersion)) }}"
          imagePullPolicy: {{ .Values.otel.image.pullPolicy }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SOLARWINDS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.secret" . }}
                  key: SOLARWINDS_API_TOKEN
                  optional: true
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" (tuple . "-common-env") }}
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.otel.gateway.otlp_endpoint.port }}
              protocol: TCP
            - name: otlp-http
              containerPort: {{ .Values.otel.gateway.otlp_endpoint.http_port }}
              protocol: TCP
{{- if .Values.otel.gateway.telemetry.metrics.enabled }}
            - name: metrics
              containerPort: {{ (split ":" .Values.otel.gateway.telemetry.metrics.address)._1 }}
              protocol: TCP
{{- end}}
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: {{ .Values.otel.gateway.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: {{ .Values.otel.gateway.readinessProbe.initialDelaySeconds }}
          resources:
{{ toYaml .Values.otel.gateway.resources | indent 12 }}
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
              readOnly: true
{{- if .Values.otel.gateway.sending_queue.offload_to_disk }}
            - name: sending-queue
              mountPath: /var/lib/swo/sending_queue
{{- end }}
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: {{ include "common.fullname" (tuple . "-gateway-config") }}
            items:
              - key: gateway.config
                path: gateway.config
{{- if .Values.otel.gateway.sending_queue.offload_to_disk }}
        - name: sending-queue
          emptyDir: {}
{{- end }}
{{- end }}