name: Check Pull Request
permissions:
    contents: read
    pull-requests: read

on:
    pull_request:
        types:
            - opened
            - edited

    workflow_dispatch:

jobs:
    check_title:
        runs-on: ubuntu-latest
        steps:
            - name: Require Issue number not to be included in PR title
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: |
                  ISSUE_NUMBER=$(echo "$PR_TITLE" | grep -oE '([[:alpha:]]+-[[:digit:]]+)' || echo "")
                  if [ -n "$ISSUE_NUMBER" ]; then
                      echo "::error::Pull Request title must not include an issue number"
                      exit 1
                  fi
