name: Install Helm Chart on Kind Cluster matrix

on:
  pull_request:
    paths-ignore:
        - docs/**
        - README.md
        - deploy/helm/*.md
        - build/**
        - src/**
    branches:
      - master
      - release/**


jobs:
  helm_verify_k8s_version:
    name: Helm verify k8s
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Kubernetes versions to test on
        kubernetes_version: [v1.25.16, v1.26.15, v1.27.16, v1.28.13, v1.29.8, v1.30.4, v1.31.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.24.0
          kubectl_version: ${{ matrix.kubernetes_version }}
          node_image: kindest/node:${{ matrix.kubernetes_version }}

      - name: Add dependency chart repos
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Download chart dependencies before linting
        run: helm dependency build deploy/helm          
      
      - name: Install Helm Chart
        run: |
          kubectl create secret generic solarwinds-api-token \
            --from-literal=SOLARWINDS_API_TOKEN=dummy-token

          helm install swo-k8s-collector ./deploy/helm  \
            --set cluster.name=kind \
            --set autoupdate.enabled=true \
            --set ebpfNetworkMonitoring.enabled=true \
            --set otel.metrics.swi_endpoint_check=false \
            --set otel.endpoint=dummy-endpoint:443 \
            --atomic          
        continue-on-error: false
      
      - name: Show all resources
        run: |
          kubectl get all